### ISSUE TITLE
Add additional claims for validFrom / validUntil

### ISSUE THREAD

**Issue by awoie** [vcstuff/draft-terbu-sd-jwt-vc#60]
Discuss whether this is needed.

**Comment by peppelinux** [comment]
I'd pose the attention to the requirement of non repudiation for long lived credentials

in OIDC Federation we have defined the historical key registry with iat and exp but also revocation status 
https://openid.net/specs/openid-connect-federation-1_0.html#name-federation-historical-keys-re

but, if the response of .well-known/jwt-issuer is in plain application/json and not signed, it is impossibile have a proof that at time T-n that issuer has those key, unless a Trusted Third Party publishes all the historical keys of the participants and the response of the jwt-issuer endpoint should be signed

this give the proof that issuer X has that metadata and that jwks at time X, since there is a signed artifact that attests that and its signature is verifiable using the historical keys hosted by a trusted third party

if non repudiation is a requirement also for you, I'd approach this problem asap

**Comment by tlodderstedt** [comment]
historical keys is not a requirement yet

**Comment by awoie** [comment]
Depending on the outcome of the W3C VCWG Miami resolution, we might actually just get rid of the translation algorithm. And then we will need to define `exp`, `iat` and `nbf` relating only to the signature (or proof) of the verifiable credential. Implementer's will then be able to use their own claims, e.g., issue_date, expiry_date (see mDL), to express the validity period of the underlying document.

**Comment by awoie** [comment]
Closing this issue if no further discussion. Direction is that exp, iat, nbf are proof-specific claims. Document-specific claims may be introduced based on the type and is out of scope of this spec.
